apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vwsfriend
resources:
- namespace.yaml
- service.yaml
- statefulset.yaml
- secret-vwsfriend.yaml
- ingress.yaml
- configmap-for-grafana.yaml
- postgresql.yaml