apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_backups.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_backupstoragelocations.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_deletebackuprequests.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_downloadrequests.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_podvolumebackups.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_podvolumerestores.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_resticrepositories.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_restores.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_schedules.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_serverstatusrequests.yaml
- https://github.com/vmware-tanzu/velero/raw/v1.6.3/config/crd/v1/bases/velero.io_volumesnapshotlocations.yaml
