apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
resources:
- namespace.yaml
- secret-valkey-users.yaml
- secret-netbox.yaml
- ocirepo-valkey.yaml
- ocirepo-netbox.yaml
- helmrelease-valkey.yaml
- helmrelease-netbox.yaml
- postgresql.yaml