apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:WGPtGDqpX5ozLiVnzdtxfLPFvLuJpsbpJW/HRUNQFXhsuv4yxedDxBtCISWKjTo2vQYnaNVd1Pe3j0czZrLB+y584nKOc42mDFa6C5NiD2uHe4deKJKg9XaX+dy1AOHnDG6Rsau819LYcriPjKR43rsOy6ua6+wKno/H7BF2arOymFi/kXW+O7aW09cfQD5S1pjd91nPOcLwZQ19/9Lc1l3+AvDs6mNgReBqbMV2o9S7xB+teheQH//CHjnjOafDDDZnpmvqDqhcFfMC9kCKrz09lBhAlQoLP8Q3VR34B4x66FpI81uUy2GR7A3R4sWZWGcmQu2mtnVlpAkdy0EHWRufcyuNvDdXTaB45GU9GRjOmip5SHiYOsk4QqBKreJPY9uZeCMcj0zMTU2dQmtKf1D2junUoERG9oSQg6vYvgLhrGiahlavq4YGYiuGgwbSKX/XxWZWVF7YpdW3IAV/n9JEF/N5QgjPxHVGwwYXYZ+X4YgYhSrQBUPi9dQpDo+8SUhWrcnZ1weYo1h8lgm+Z89Or8b20oz5J3EmOhSY7VyZh9xfpfpl3cD/mJ2lg/tvy1EK6rE4gqSQkohwf9pWcNuJlAgRG0hiz53nyZEJi0jEvQr77p9EUsCeQpSTRn3J52NSkGpMzaa7J3UJQ8bydTLSG6AOM4YJtmJGjdMWrz6X77EpS5j8sjLa5ylrr4rOlLGP7nW+E5ZSnV0F8VjplyUE3vsgK/o13oKTxqejTET5wAggnfDz/fob239ZWUeMzH0EWjbMGreITS+w,iv:OfyIjN/UB5o+UPKN2a2BxzibM0Fo4Loyk7UyHwfgh+k=,tag:S+gfJdKb5ibcspMZgeI5oQ==,type:str]
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-08T17:48:26Z'
    mac: ENC[AES256_GCM,data:byHvznQJb0t/pz8Cckq2FvNnY4rlP9iTQCw1dIIlriR8UGzx5Mvha6x9rKREIdNPA069wJu6N3+9+QEvW6eiPApOywF0iGwvYvsIR4HSXMEfGE9thS7/yFPw6ytCsnM9T9OXBDQeEBZP+eIzXDWaKnUaLijLlUmKpjq8yRDyiY4=,iv:U9Vb8DMyxqjQUqtkfC9+sFxCkhc+JlErYXf6etaNhM0=,tag:UeTY9fRoGDUNQbrljOJVRA==,type:str]
    pgp:
    -   created_at: '2021-02-22T18:54:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAAhSHjZVj/Lrn98rOz0Eg7doH0z/ixzCATo7rctWeqYx+H
            8WgmvBA2MegPPpQitY4gamqfvt7AhNBGaNIgZ3DQVqrHXNTtqN/YmlmXvH1+C6d0
            vALFmr87co6hqjAEwQVsz5Ro/DMWVmIFxdgFSrB8WpEc8q2cSSNs50PEr94ZIYGq
            Fr1uXGxAQ6VnTUULSGh77SD1cYtj3+K34konBLsT7PVwEGoAEbEHegKgcH1BVARE
            EsHkJ8KM8JFB0FIj1AFokHH/8nO4Np1/gIiU0RyAJCRwEAOgGsP9lIlCdKukFgT4
            fJwUDEeCpcYWu1FpT2iplLZ/d+wixYY1eED+rBmVIiD5mAD7C876q4SteUJhlC0F
            w1c6LENw6Mho0quVymaIhYjx+s8MD3M7ReZpe0Lvxa1HeibhMCQobXTm55H+2B21
            QKrfYIknifZeR/ALVehBPVf1xdwgcWLzf9oY3sXXrUbqas2rAGGB4KbpENAnbOxb
            II5sQ0Bqh1VgM2StP4lXmOJS9JPSHC4ZfEh812wAltMDw5zjl9Zlo0hrNL67QCiG
            G/oL283PQT3NX3Nysvv5mvufBaYCLmCLxibPwXNH1kElTd6KjBVaFRf9y1kirBme
            GclVtnzkcZMIjDB1RfzigITLhubXKSscFqBYzYqNrO1+iXQkpQTXkHNvcEflHf/S
            XAEXlSx0iMzYw6bcmJyC2Fy0fAbpkOSB0g1wa8DVClj3lMqnAykNOe6b32r7kHbM
            TNlQOTz8RNMqBjrYMVLzNCDyvk1fki11OaIEiTG40cdrXxBewSObflxf97gd
            =l4qZ
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
